[project]
name = "automate-stategy-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "firebase-admin>=7.1.0",
    "pycryptodome>=3.23.0",
    "requests>=2.32.4",
    "termcolor>=3.1.0",
]
